default_agent: cipher_quest_agent
agents:
  cipher_quest_agent:
    name: cipher_quest_agent
    entrypoint: /home/ubuntu/environment/GameDay/cipher-quest/cipher_command_agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /home/ubuntu/environment/GameDay/cipher-quest
    aws:
      execution_role: arn:aws:iam::390402546551:role/CipherQuestExecutionRole
      execution_role_auto_create: true
      account: '390402546551'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-390402546551-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: cipher_quest_agent-iAy1VHEbAY
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:390402546551:runtime/cipher_quest_agent-iAy1VHEbAY
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: cipher_quest_agent_mem-uljlxS71lX
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:390402546551:memory/cipher_quest_agent_mem-uljlxS71lX
      memory_name: cipher_quest_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
